/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JButton;

/**
 *
 * @author pablo
 */
public class Teclado extends javax.swing.JPanel {

    
    public Teclado() {
        initComponents();
        
        var letras = new ArrayList<>(Arrays.asList(
            'Q','W','E','R','T','Y','U','I','O','P','A','S','D','F','G',
               'H','J','K','L','Ñ','ç','Z','X','C','V','B','N','M', '-', '*'
        ));
        
        letras.forEach((l) -> {
            add(new JButton(l.toString()));
        });

        System.out.println("creado");
        this.setVisible(true);
         repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(3, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
