package vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modelo.Juego;

/**
 *
 * @author Pablo Jiménez Jiménez
 */
public class VistaGrafica extends javax.swing.JFrame implements ActionListener {

    private Juego juego;
    private ArrayList<ImageIcon> figuras; // Imagen es un jPanel

    public VistaGrafica() {
        
        this.centrarPantalla();
        
        initComponents();
        this.setTitle("Ahorcado ~ Pablo Jj");
        this.juego = new Juego(pedirPalabra());
        this.cargarTeclado();
        this.cargarImagenes();
        this.palabra.setText(juego.getPalabra_cifrada());
        
        
        this.cargarImagenes();
        
        this.setResizable(false);
        this.refrescar();
        this.setVisible(true);
        this.repaint();
        this.revalidate();
    }
    
    private void centrarPantalla() {
        
        //Toolkit tk = new Toolkit();
        
        
    }

    private void cargarTeclado() {

        // Para que si se llama en otras ocasiones escriba sobre una lámina limpia
        this.panel_teclado.removeAll();
        ArrayList<Character> teclado = juego.getPosibles();

        for (char c : teclado) {
            JButton btn = new JButton(Character.toString(c));

            btn.addActionListener(this);

            btn.setFont(new Font("Arial", Font.BOLD, 22));
            panel_teclado.add(btn);
        }
    }

    private void cargarImagenes() {
        figuras = new ArrayList<>();

        for (int i = 1; i <= 6; i++) {
            figuras.add(new ImageIcon("/Users/pablojj/Documents/Mis_proyectos/ahorcado_2.0/src/vista/img/" + i + "_foto.png"));
        }
        
        panel_foto.setIcon(figuras.get( 0 ));
    }

    private String pedirPalabra() {
        String seleccion;
        do {
            seleccion = JOptionPane.showInputDialog(
                    this,
                    "Introduce palabra a adivinar",
                    "PALABRA SECRETA",
                    JOptionPane.QUESTION_MESSAGE);
        } while (seleccion.contains(" ") || seleccion.isBlank() || seleccion.isEmpty());

        return seleccion;
    }

    private void refrescar() {
        palabra.setText(juego.getPalabra_cifrada());
        System.err.println("indice = " + juego.getIndiceFigura());

        int i = juego.getIndiceFigura();
        System.out.println("== cambio imagen ==");        
        panel_foto.setIcon(figuras.get( i ));
        panel_foto.repaint();
        this.repaint();       
    }

    /**
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        palabra = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panel_teclado = new javax.swing.JPanel();
        panel_foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setText("Nueva Partida");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        palabra.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        palabra.setText("jLabel2");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        panel_teclado.setLayout(new java.awt.GridLayout(3, 10));

        panel_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/1_foto.png"))); // NOI18N
        panel_foto.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(palabra))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(panel_teclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panel_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palabra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(panel_teclado, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(panel_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.gestionarNuevaPartida();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gestionarNuevaPartida() {
        String palabra = pedirPalabra();
        juego = new Juego(palabra);
        this.cargarTeclado();
        this.refrescar();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel palabra;
    private javax.swing.JLabel panel_foto;
    private javax.swing.JPanel panel_teclado;
    // End of variables declaration//GEN-END:variables

    
    /**
     * Gestiona las pulsaciones de las teclas.
     * @param e El desencadenante de la acción
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        if (!juego.finalJuego()) {
            String source = e.getActionCommand();

            
            boolean da = juego.sigPaso(source.charAt(0));
            
            if (da) {
                JButton btn = (JButton) e.getSource();
                btn.setForeground(new Color(28, 209, 85));
            } else {
                JButton btn = (JButton) e.getSource();
                btn.setForeground(new Color(203, 19, 23));
                btn.setEnabled(false);
            }
            refrescar();
        } 

        if (juego.finalJuego()) {

            String sms = (juego.ganador()) ? "¡HAS GANADO!" : "Has perdido";

            JOptionPane.showMessageDialog(this, sms, "Fin de la partida", 1);
            gestionarNuevaPartida();
        }
    }
}
